Docker image build and push using GitHub Actions
nativefier/nativefier pull request #1100
Opened 2021-01-16 22:32 UTC by snpranav

Due to issue #848, I don't think we can rely on the Docker Hub auto-builds to have the latest image. Hence, I wrote a workflow to build and push the docker image to the Github Container Registry ([ghcr.io](https://ghcr.io/)).

For it to work, a personal access token needs to be added to the secrets of the repository to be able to authenticate with the docker registry. The secret must be stored with the name `CR_PAT`.

Once this is set up, the community can maintain the workflow to build and push the latest docker images.

2021-01-16 22:42 UTC, ronjouch commented
Hi @snpranav, thanks for the initiative! Jia (original author of Nativefier, and managing our publishing) is going to look at it.

2021-01-20 13:34 UTC, jiahaog commented
Thanks for the contribution! It's unfortunate that the automated builds on DockerHub are just not working for some unknown reason :(

Just some preliminary feedback here – do you think it would be better to add this as another step to the [CI workflow](https://github.com/jiahaog/nativefier/blob/master/.github/workflows/ci.yml)? I'm not really about the conventions of GitHub actions, but it does seem like it would be useful to do this publishing step only after the tests run and have passed.

Also, can we push the images to DockerHub instead since users are already using that repository? Happy to provide the credentials if so 🙂

2021-01-20 23:30 UTC, snpranav commented
Hi @jiahaog,
Thanks for reviewing the pull request.

> Just some preliminary feedback here – do you think it would be better to add this as another step to the [CI workflow](https://github.com/jiahaog/nativefier/blob/master/.github/workflows/ci.yml)? I'm not really about the conventions of GitHub actions, but it does seem like it would be useful to do this publishing step only after the tests run and have passed.

Haha. I'm used to GitLab CI, so GitHub actions are quite new to me also :smile:. Nevertheless, I have updated the docker build and the push process to happen in the [CI file](https://github.com/jiahaog/nativefier/blob/master/.github/workflows/ci.yml) after the test job passes.

The reason the docker build test in the pull request is failing is that two secrets in the Github repository are missing.
You need to add the following secrets to the GitHub repository.
1. `DOCKERHUB_USERNAME` - Set it to your Docker Hub username (in this case I'm guessing it would just be `jiahaog`).
2. `DOCKERHUB_TOKEN` - Set it to the personal access token from Docker Hub.

Once you add these secrets the CI pipeline will run the tests, build the docker image and push it to Docker Hub with the latest tag and the short commit SHA tag.

2021-01-26 11:58 UTC, jiahaog approved these changes
Sorry for the delay, I've been a bit busy. But thanks a lot for the contribution! Just a few nits about quoting the shell variables, and we can merge this :)

2021-01-26 11:58 UTC, jiahaog commented on .github/workflows/ci.yml
> +        run: docker build . --file Dockerfile --tag $IMAGE_ID:latest
```suggestion
        run: docker build . --file Dockerfile --tag "$IMAGE_ID:latest"
```

2021-01-26 11:58 UTC, jiahaog commented on .github/workflows/ci.yml
> +          docker tag $IMAGE_ID:latest $IMAGE_ID:${GITHUB_SHA::8}
```suggestion
          docker tag "$IMAGE_ID:latest" "$IMAGE_ID:${GITHUB_SHA::8}"
```

2021-01-26 11:58 UTC, jiahaog commented on .github/workflows/ci.yml
> +          docker push $IMAGE_ID:${GITHUB_SHA::8}
```suggestion
          docker push "$IMAGE_ID:latest"
          docker push "$IMAGE_ID:${GITHUB_SHA::8}"
```

2021-01-26 20:52 UTC, snpranav commented
Just incorporated the suggestions into this PR. Thanks for approving the PR and creating this repository @jiahaog.
Thanks @ronjouch for your amazing contribution and maintaining this repository. :smile: :partying_face: 

@jiahaog, I don't think you have put in your credentials for DockerHub in the secrets as specified in my previous commend. The workflow is failing in the PR due to this.

2021-01-27 14:22 UTC, jiahaog commented
Oh, I think you won't be able to access the secrets anyway in a pull request - see https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow. I was intending to add the secrets then merge this to test if the workflow works, I'm pretty confident you did a good job :)

However... as I was looking for the secrets just now, it seems like Docker Hub has magically started working again... 
<img width="1007" alt="Screen Shot 2021-01-27 at 22 17 15" src="https://user-images.githubusercontent.com/7111741/106003705-6bfa1800-60ed-11eb-9f0a-b220ddde4766.png">

I think they might have fixed this on their end. I'd rather let Docker Hub take care of this instead of having to maintain our workflows, would you be alright if we keep this around for a couple of weeks and see how it goes? If Docker Hub stops working again we should definitely merge this pull request. So sorry for the extra work you had to do.

2021-02-26 01:01 UTC, ronjouch commented
> I think they might have fixed this on their end. I'd rather let Docker Hub take care of this instead of having to maintain our workflows, would you be alright if we keep this around for a couple of weeks and see how it goes? If Docker Hub stops working again we should definitely merge this pull request. So sorry for the extra work you had to do.

I confirm that Docker seems to work again now. I just made a new release, and I see Docker Hub picked up on it.

With that, like Jia said, @snpranav thanks for all your work 🙂.

Feel free to chime in here or at https://github.com/nativefier/nativefier/issues/848 if Docker Hub starts lagging again.

2021-12-16 04:37 UTC, snpranav commented
@jiahaog @ronjouch As mentioned in #848, the docker auto builds have stopped again. I would advocate for reconsidering accepting this pull request as fixing the docker hub auto builds always takes a really long time (this time it has been 5 months and still not fixed).

2021-12-17 03:21 UTC, ronjouch requested changes
> As mentioned in #848, the docker auto builds have stopped again. I would advocate for reconsidering accepting this pull request as fixing the docker hub auto builds always takes a really long time (this time it has been 5 months and still not fixed).

@snpranav yup, agreed. We gave Docker Hub's auto-build a try and it would have been the ideal solution, but it's still too broken. Oh well.

This PR needs a rework, though. It's set to happen in CI, for *all builds* including PR builds! This means all WIP PRs running CI will push to Docker, and we certainly do not want that :scream: . Please move your new job to `publish.yml`, not `ci.yml`

2021-12-17 04:21 UTC, snpranav commented
@ronjouch Good catch :sweat_smile: , I just moved the docker build actions from `ci.yml` file to the `publish.yml`. Let me know if you see any other issues with the docker build action :)

2022-01-05 11:43 UTC, snpranav commented
Hi @ronjouch , I implemented the changes you had requested in this PR a few weeks ago. Could you please tell me if there's any status update on this PR?

Reference - #848

2022-01-06 15:13 UTC, ronjouch approved these changes

2022-01-06 15:14 UTC, merged

2022-01-06 16:02 UTC, ronjouch commented
@snpranav confirmed working, thanks! https://github.com/nativefier/nativefier/issues/848#issuecomment-1006706120