Make app strict TypeScript + linting (and add a shared project)
nativefier/nativefier pull request #1231
Opened 2021-06-17 04:34 UTC by TheCleric

Sequel to #1223 . Now the whole repo should be strict!

2021-06-18 04:00 UTC, ronjouch requested changes

2021-06-18 17:54 UTC, TheCleric commented on app/.eslintrc.js
>    rules: {
I thought about trying to make a base one that these import, but not sure how well that would work. What do you think?

2021-06-18 17:55 UTC, TheCleric commented on app/package.json
> +    "electron-context-menu": "^3.1.0",
Yep!

2021-06-18 17:58 UTC, TheCleric commented on src/infer/inferIcon.ts
> +import pageIcon from 'page-icon';
Yep! It's actually what TypeScript (or ESLint?) wanted. It did NOT work at first, but was resolved by setting `"esModuleInterop": true,` in the `tsconfig-base.json`

2021-06-18 18:05 UTC, TheCleric commented on app/src/helpers/windowEvents.ts
> +import { WindowOptions } from '../../../shared/src/options/model';
Yep. I did the following:
- `npm pack`
- `npm i -g ./nativefier-44.0.4.tgz`
- `nativefier https://google.com ~/Downloads`
- Verified the app launched.

I didn't see an exact recipe there, so let me know if this is insufficient

2021-06-18 18:06 UTC, TheCleric commented on app/src/helpers/windowEvents.ts
> +  // IpcMainEvent,
```suggestion
```

2021-06-18 18:06 UTC, TheCleric commented on src/.eslintrc.js
> +    'app/lib/**',
Good point.

2021-06-18 18:08 UTC, TheCleric commented on src/.eslintrc.js
> +module.exports = {
Yeah I replied to one of your other comments wondering that myself. I'll attempt it.

2021-06-20 23:50 UTC, ronjouch commented on src/.eslintrc.js
> +module.exports = {
@TheCleric okay. For me to understand: why the split into several `.eslintrc`s ?

2021-06-20 23:52 UTC, ronjouch commented on app/src/helpers/windowEvents.ts
> +import { WindowOptions } from '../../../shared/src/options/model';
Yeah that's it 👍

2021-06-21 02:45 UTC, TheCleric commented on src/.eslintrc.js
> +module.exports = {
Because each has its own slightly different tsconfig.json since each is its own ts project and you have to reference one tsconfig per eslintrc.

2021-06-21 17:56 UTC, ronjouch commented on src/.eslintrc.js
> +module.exports = {
> you have to reference one tsconfig per eslintrc.

Thx, that's what I had missed.

I like what you did with sharing what can be shared, by accessing `base.{plugins, parser, extends, rules}`. Neat.

2021-06-22 01:18 UTC, TheCleric commented on src/.eslintrc.js
> +module.exports = {
Thanks!

2021-06-22 01:19 UTC, TheCleric commented
Let me know if there's anything else you'd like done here @ronjouch :)

2021-06-22 02:32 UTC, ronjouch approved these changes
> Let me know if there's anything else you'd like done here

@TheCleric nope, all good.

1. Letting you merge this before/after https://github.com/nativefier/nativefier/pull/1235 as you want
2. Tell me if you want a release before you merge this. Right now, the only code commit since strict CLI (44.0.4) is https://github.com/nativefier/nativefier/pull/1229 .

2021-06-22 05:22 UTC, TheCleric commented
> 1. Letting you merge this before/after https://github.com/nativefier/nativefier/pull/1235 as you want
> 
> 2. Tell me if you want a release before you merge this. Right now, the only code commit since strict CLI (44.0.4) is https://github.com/nativefier/nativefier/pull/1229 .

Let's merge 1235, cut a release, merge this, then cut another. As well there's a new Electron 12.

2021-06-25 20:23 UTC, ronjouch commented
> Let's merge 1235, cut a release, merge this, then cut another. As well there's a new Electron 12.

@TheCleric I just released 44.0.5 with the recent tray/zoom/externalurl fixes, and an Electron bump. Letting you rebase & merge this whenever convenient, and I'll cut a release.

2021-06-26 13:59 UTC, merged

2021-06-26 14:01 UTC, TheCleric commented
Merged!

2021-06-26 14:56 UTC, ronjouch commented
> Merged!

:tada: ! Released as [44.0.6](https://github.com/nativefier/nativefier/releases/tag/v44.0.6).